const SAMPLE_DATA = [
    {
        prompt: 'Generate an entity relationship diagram for library management',
        diagram:
            'erDiagram\n    CUSTOMER ||--o{ BORROWING : borrows\n    CUSTOMER {\n        int customer_id PK\n        string name\n        string address\n        string phone\n    }\n    BORROWING {\n        int borrowing_id PK\n        int customer_id FK\n        int book_id FK\n        date borrow_date\n        date due_date\n        date return_date\n    }\n    BOOK ||--o{ BORROWING : is_borrowed_on\n    BOOK {\n        int book_id PK\n        string title\n        string isbn\n        int publisher_id FK\n        int author_id FK\n        int category_id FK\n    }\n    PUBLISHER ||--|{ BOOK : publishes\n    PUBLISHER {\n        int publisher_id PK\n        string name\n        string address\n    }\n    AUTHOR ||--|{ BOOK : writes\n    AUTHOR {\n        int author_id PK\n        string name\n        string bio\n    }\n    CATEGORY ||--|{ BOOK : belongs_to\n    CATEGORY {\n        int category_id PK\n        string name\n    }',
    },
    {
        prompt: 'Generate sequence diagram for simple LLM app',
        diagram:
            'sequenceDiagram\n    participant User\n    participant Application\n    participant LLM API\n    participant Model\n\n    User->>Application: Input prompt\n    activate Application\n    Application->>LLM API: Send prompt request\n    activate LLM API\n    LLM API->>Model: Forward prompt\n    activate Model\n    Model-->>LLM API: Generate response\n    deactivate Model\n    LLM API-->>Application: Return response\n    deactivate LLM API\n    Application-->>User: Display response\n    deactivate Application',
    },
    {
        prompt: 'Generate a user journey of people going to work',
        diagram:
            'graph TD\n    A[Start] --> B{Wake Up};\n    B -- Alarm goes off --> C{Snooze Alarm?};\n    B -- No alarm --> C;\n    C -- Yes --> B;\n    C -- No --> D{Get Out of Bed};\n    D --> E{Bathroom Routine};\n    E --> F{Get Dressed};\n    F --> G{Eat Breakfast?};\n    G -- Yes --> H{Prepare/Eat Breakfast};\n    G -- No --> I{Prepare for Commute};\n    H --> I;\n    I --> J{Choose Commute Method};\n    J -- Drive --> K{Drive to Work};\n    J -- Public Transport --> L{Walk to Station/Stop};\n    J -- Walk/Bike --> M{Walk/Bike to Work};\n    L --> N{Wait for Transport};\n    N --> O{Ride Transport};\n    O --> P{Get off at Destination};\n    P --> Q{Walk to Workplace};\n    K --> R{Park Car};\n    R --> Q;\n    M --> Q;\n    Q --> S[Arrive at Work];\n    S --> T{Start Workday};',
    },
    {
        prompt: 'Generate a mindmap visualizing history of Canada',
        diagram:
            "graph LR\n    A[Canada History] --> B(Pre-Colonial Era);\n    A --> C(European Colonization);\n    A --> D(British North America);\n    A --> E(Confederation & Expansion);\n    A --> F(20th Century);\n    A --> G(Contemporary Canada);\n\n    B --> B1(Indigenous Peoples);\n    B1 --> B1A(First Nations);\n    B1 --> B1B(Inuit);\n    B1 --> B1C(Métis);\n    B --> B2(Diverse Cultures & Societies);\n    B --> B3(Oral Traditions & History);\n\n    C --> C1(French Exploration & Settlement);\n    C1 --> C1A(New France);\n    C1 --> C1B(Fur Trade);\n    C --> C2(British Conquest);\n    C2 --> C2A(Seven Years' War);\n    C2 --> C2B(Treaty of Paris 1763);\n    C --> C3(Early British Rule);\n\n    D --> D1(American Revolution Impact);\n    D --> D2(War of 1812);\n    D --> D3(Rebellions of 1837-1838);\n    D3 --> D3A(Upper Canada Rebellion);\n    D3 --> D3B(Lower Canada Rebellion);\n    D --> D4(Responsible Government Movement);\n\n    E --> E1(Confederation 1867);\n    E1 --> E1A(Fathers of Confederation);\n    E1 --> E1B(Dominion of Canada);\n    E --> E2(Expansion Westward);\n    E2 --> E2A(Transcontinental Railway);\n    E2 --> E2B(North-West Mounted Police);\n    E --> E3(Indigenous Treaties & Resistance);\n    E --> E4(Growth of Provinces & Territories);\n\n    F --> F1(World War I);\n    F1 --> F1A(Conscription Crisis);\n    F1 --> F1B(Vimy Ridge);\n    F --> F2(Interwar Period);\n    F2 --> F2A(Great Depression);\n    F2 --> F2B(Rise of Social Programs);\n    F --> F3(World War II);\n    F --> F4(Post-War Boom);\n    F4 --> F4A(Baby Boom);\n    F4 --> F4B(Suburbanization);\n    F --> F5(Cold War);\n    F --> F6(Quiet Revolution in Quebec);\n    F6 --> F6A(Separatism);\n\n    G --> G1(Multiculturalism);\n    G --> G2(Charter of Rights and Freedoms 1982);\n    G --> G3(Constitutional Debates);\n    G3 --> G3A(Meech Lake Accord);\n    G3 --> G3B(Charlottetown Accord);\n    G --> G4(Indigenous Rights & Reconciliation);\n    G --> G5(Globalization & Economic Change);\n    G --> G6(21st Century Challenges);\n    G6 --> G6A(Climate Change);\n    G6 --> G6B(Technological Advancements)",
    },
]

export { SAMPLE_DATA }
